spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    producer:
      bootstrap-servers: nonprod:9092,nonprod:9093,nonprod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5
